---
title: "Sensitivity Analysis"
author: "Robert Saldivar and Madeline Gorchels"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
#Loading packages for sensitivity analysis
library(tidyverse)
library(sensitivity)
library(pse)
library(gridExtra)


```

```{r, message=FALSE, warning=FALSE}
# Sensitivity Analysis
# All parameters varied

source("Almond_Yield.R")


#Setting up standard deviation of 20%
sd1 = 0.015*0.2
sd2 = 0.0046*0.2
sd3 = 0.07*0.2
sd4 = 0.0043*0.2
sd5 = 0.28*0.2


# read in the input data
clim=read_csv("climate_input.csv")%>%
  rename(min_temp = min_T.y)%>%
  rename(precip = precip.x)


```



```{r}
# Sensitivity Analysis using LHS
# generate samples from LHS


# Lets consider all parameters....
factors = c("min_temp_coeff", "min_temp_coeff2", "precip_coeff", "precip_coeff2", "intercept")

# Decide How many parameter sets to run
nsets=500


# choose distributions for parameters - 
q = c("qnorm", "qnorm", "qnorm", "qnorm", "qnorm")
q.arg = list(list(mean=-0.015,sd=sd1), list(mean=-0.0046, sd=sd2), list(mean=-0.07, sd=sd3), list(mean=0.0043, sd=sd4), list(mean=0.28, sd=sd5))


sens_almond = LHS(NULL,factors,nsets,q,q.arg)
sens_pars = get.data(sens_almond)

```


```{r, message=FALSE, warning=FALSE, ouput=FALSE}
# Rank and Graph of LHS
source("yield_anom.R")


# create a data structure to store results
sens_results = matrix(nrow=nsets, ncol=1)


#apply our function to the sensativity parameters 
sens_1_run= mapply(FUN=yield_anomaly,
            min_temp_coeff=sens_pars$min_temp_coeff,
            min_temp_coeff2=sens_pars$min_temp_coeff2,
            precip_coeff=sens_pars$precip_coeff, 
            precip_coeff2=sens_pars$precip_coeff2, 
            intercept=sens_pars$intercept, 
            MoreArgs=list(climate=clim))
#head(sens_1_run)
```


```{r}
# ger results into a graphable format
sens_results = matrix((unlist(sens_1_run)), ncol=1, byrow=TRUE)


colnames(sens_results) = c("mean_yield")



# to take advantage of LHS/pse functions for plotting interesting information we can send results back
sens_almond = pse::tell(sens_almond, t(sens_results), res.names=c("mean_yield"))
pse::plotscatter(sens_almond, col="blue", cex=5) 
pse::plotprcc(sens_almond) 
sens_almond$prcc


```

```{r}
LHS_results = as.data.frame(sens_results)

# look at the senativity of each parameter
sens_yield_LHS= pse::tell(sens_almond, t(LHS_results))
sens_yield_LHS


LHS_plot= ggplot(data = LHS_results, aes(y = mean_yield))+
  geom_boxplot()+
  labs(y = "Mean Yearly Yield", title = "Sensitivity of Yearly Yields on Model Parameters")+
  theme_classic()
LHS_plot
```



```{r, message=FALSE, warning=FALSE}
# Sensitivity Analysis Using Sobel Method

source("Almond_Yield.R")
# names of parameters
# number of paramets

nsets = 500
min_temp_coeff = rnorm(mean = -0.015, sd = 0.2, n = nsets)
min_temp_coeff2 = rnorm(mean = -0.0046, sd = 0.2, n = nsets)
precip_coeff = rnorm(mean = -0.07, sd = 0.2, n = nsets)
precip_coeff2 = rnorm(mean = 0.0043, sd = 0.2, n = nsets)
intercept = rnorm(mean = 0.28, sd = 0.2, n = nsets)
min_temp = rep_len(clim$min_temp, length.out = nsets)
precip = rep_len(clim$precip, length.out = nsets)



#Generating the first set of random numbers

random_v1 = cbind.data.frame(min_temp_coeff, min_temp_coeff2, precip_coeff, precip_coeff2, intercept, min_temp, precip)

# Generating a second set of random variables
nsets = 500
min_temp_coeff = rnorm(mean = -0.015, sd = 0.2, n = nsets)
min_temp_coeff2 = rnorm(mean = -0.0046, sd = 0.2, n = nsets)
precip_coeff = rnorm(mean = -0.07, sd = 0.2, n = nsets)
precip_coeff2 = rnorm(mean = 0.0043, sd = 0.2, n = nsets)
intercept = rnorm(mean = 0.28, sd = 0.2, n = nsets)
min_temp = rep_len(clim$min_temp, length.out = nsets)
precip = rep_len(clim$precip, length.out = nsets)


random_v2 = cbind.data.frame(min_temp_coeff, min_temp_coeff2, precip_coeff, precip_coeff2, intercept, min_temp, precip)

sens_results_sobol1 = sobol2007(model = NULL, random_v1, random_v2, nboot = 100)

# Running the model for all parameter sets

sobol1_res = mapply(FUN = Almond_Yield,
                    min_temp_coeff=sens_results_sobol1$X$min_temp_coeff,
                    min_temp_coeff2=sens_results_sobol1$X$min_temp_coeff2,
                    precip_coeff=sens_results_sobol1$X$precip_coeff,
                    precip_coeff2=sens_results_sobol1$X$precip_coeff2,
                    intercept=sens_results_sobol1$X$intercept,
                    min_temp=sens_results_sobol1$X$min_temp,
                    precip=sens_results_sobol1$X$precip
                    )



sens_almond_sobol1 = sensitivity::tell(sens_results_sobol1, sobol1_res, res.names="mean_yield")

# first-order indices (main effect without co-variance)
sens_almond_sobol1$S

# total sensitivity index - note that this partitions the output variance - so values sum to 1
sens_almond_sobol1$T

print(sens_almond_sobol1)
plot(sens_almond_sobol1)

# making a datafram for plotting
both1 = cbind.data.frame(sens_almond_sobol1$X, yield=sens_almond_sobol1$y)

# Looking at the response to the two most important variables
ggplot(both1, aes(precip_coeff2, yield, col = precip_coeff)) +
  geom_point() +
  labs(x = "Precipitation Coefficient 2", y = "Yield Anamoly") +
  theme_classic()

ggplot(both1, aes(y = yield)) +
  geom_boxplot() +
  theme_classic()



```


```{r}
# LHS Sensitivity Analysis using twice as many parameters

nsets2=1000


# choose distributions for parameters - 
q = c("qnorm", "qnorm", "qnorm", "qnorm", "qnorm")
q.arg = list(list(mean=-0.015,sd=sd1), list(mean=-0.0046, sd=sd2), list(mean=-0.07, sd=sd3), list(mean=0.0043, sd=sd4), list(mean=0.28, sd=sd5))


sens_almond2 = LHS(NULL,factors,nsets2,q,q.arg)
sens_pars2 = get.data(sens_almond2)

```


```{r, message=FALSE, warning=FALSE, ouput=FALSE}
# Rank and Graph of LHS
source("yield_anom.R")


# create a data structure to store results
sens_results2 = matrix(nrow=nsets2, ncol=1)


#apply our function to the sensativity parameters 
sens_2_run= mapply(FUN=yield_anomaly,
            min_temp_coeff=sens_pars2$min_temp_coeff,
            min_temp_coeff2=sens_pars2$min_temp_coeff2,
            precip_coeff=sens_pars2$precip_coeff, 
            precip_coeff2=sens_pars2$precip_coeff2, 
            intercept=sens_pars2$intercept, 
            MoreArgs=list(climate=clim))
#head(sens_1_run)

sens_results2 = matrix((unlist(sens_2_run)), ncol=1, byrow=TRUE)


colnames(sens_results2) = c("mean_yield")


# to take advantage of LHS/pse functions for plotting interesting information we can send results back
sens_almond2 = pse::tell(sens_almond2, t(sens_results2), res.names=c("mean_yield"))
pse::plotscatter(sens_almond2, col="blue", cex=5) 
pse::plotprcc(sens_almond2) 
sens_almond2$prcc
```


```{r}
# Using Sobel with twice as many parameter


# Sensitivity Analysis Using Sobel Method

source("Almond_Yield.R")
# names of parameters
# number of paramets

nsets = 1000
min_temp_coeff = rnorm(mean = -0.015, sd = 0.2, n = nsets)
min_temp_coeff2 = rnorm(mean = -0.0046, sd = 0.2, n = nsets)
precip_coeff = rnorm(mean = -0.07, sd = 0.2, n = nsets)
precip_coeff2 = rnorm(mean = 0.0043, sd = 0.2, n = nsets)
intercept = rnorm(mean = 0.28, sd = 0.2, n = nsets)
min_temp = rep_len(clim$min_temp, length.out = nsets)
precip = rep_len(clim$precip, length.out = nsets)



#Generating the first set of random numbers

random_v3 = cbind.data.frame(min_temp_coeff, min_temp_coeff2, precip_coeff, precip_coeff2, intercept, min_temp, precip)

# Generating a second set of random variables
nsets = 1000
min_temp_coeff = rnorm(mean = -0.015, sd = 0.2, n = nsets)
min_temp_coeff2 = rnorm(mean = -0.0046, sd = 0.2, n = nsets)
precip_coeff = rnorm(mean = -0.07, sd = 0.2, n = nsets)
precip_coeff2 = rnorm(mean = 0.0043, sd = 0.2, n = nsets)
intercept = rnorm(mean = 0.28, sd = 0.2, n = nsets)
min_temp = rep_len(clim$min_temp, length.out = nsets)
precip = rep_len(clim$precip, length.out = nsets)


random_v4 = cbind.data.frame(min_temp_coeff, min_temp_coeff2, precip_coeff, precip_coeff2, intercept, min_temp, precip)

sens_results_sobol2 = sobol2007(model = NULL, random_v3, random_v4, nboot = 100)

# Running the model for all parameter sets

sobol2_res = mapply(FUN = Almond_Yield,
                    min_temp_coeff=sens_results_sobol2$X$min_temp_coeff,
                    min_temp_coeff2=sens_results_sobol2$X$min_temp_coeff2,
                    precip_coeff=sens_results_sobol2$X$precip_coeff,
                    precip_coeff2=sens_results_sobol2$X$precip_coeff2,
                    intercept=sens_results_sobol2$X$intercept,
                    min_temp=sens_results_sobol2$X$min_temp,
                    precip=sens_results_sobol2$X$precip
                    )



sens_almond_sobol2 = sensitivity::tell(sens_results_sobol2, sobol2_res, res.names="mean_yield")

# first-order indices (main effect without co-variance)
sens_almond_sobol2$S

# total sensitivity index - note that this partitions the output variance - so values sum to 1
sens_almond_sobol2$T

print(sens_almond_sobol2)
plot(sens_almond_sobol2)

# making a datafram for plotting
both2 = cbind.data.frame(sens_almond_sobol2$X, yield=sens_almond_sobol2$y)

# Looking at the response to the two most important variables
ggplot(both2, aes(precip_coeff2, yield, col = precip_coeff)) +
  geom_point() +
  labs(x = "Precipitation Coefficient 2", y = "Yield Anamoly") +
  theme_classic()

ggplot(both2, aes(y = yield)) +
  geom_boxplot() +
  theme_classic() +
  scale_y_continuous()

```

